language: php

php:
  - 7.0
  - 7.1

env:
  - TRAVIS_NODE_VERSION="6"

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash
  - wget https://getcomposer.org/composer.phar
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

install:
  - phing test-init
  - phing test-regenerate-database
  - cp phpunit.xml.dist phpunit.xml
  - cp behat.yml.dist behat.yml

script:
  - phing test-run-tests
  - npm test