---
  - name: Tweak PHP Opcache config
    copy:
      src: files/php-opcache.ini
      dest: /etc/php/7.0/fpm/conf.d/10-opcache.ini
    notify:
      - restart apache
  - name: Enable apcu
    lineinfile:
      dest: /etc/php/7.0/cli/conf.d/20-apcu.ini
      state: present
      line: "apc.enable_cli = On"
    notify:
      - restart apache